(function() {var implementors = {
"bitvec":[["impl&lt;T = <a class=\"primitive\" href=\"https://doc.rust-lang.org/1.73.0/std/primitive.usize.html\">usize</a>, O = <a class=\"struct\" href=\"bitvec/order/struct.Lsb0.html\" title=\"struct bitvec::order::Lsb0\">Lsb0</a>&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bitvec/slice/struct.BitSlice.html\" title=\"struct bitvec::slice::BitSlice\">BitSlice</a>&lt;T, O&gt;",1,["bitvec::slice::BitSlice"]]],
"bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bytes/buf/struct.UninitSlice.html\" title=\"struct bytes::buf::UninitSlice\">UninitSlice</a>",1,["bytes::buf::uninit_slice::UninitSlice"]]],
"cs_serde_bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"cs_serde_bytes/struct.Bytes.html\" title=\"struct cs_serde_bytes::Bytes\">Bytes</a>",1,["cs_serde_bytes::bytes::Bytes"]]],
"icu_properties":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"icu_properties/provider/names/struct.NormalizedPropertyNameStr.html\" title=\"struct icu_properties::provider::names::NormalizedPropertyNameStr\">NormalizedPropertyNameStr</a>",1,["icu_properties::provider::names::NormalizedPropertyNameStr"]]],
"indexmap":[["impl&lt;K, V&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"indexmap/map/struct.Slice.html\" title=\"struct indexmap::map::Slice\">Slice</a>&lt;K, V&gt;",1,["indexmap::map::slice::Slice"]],["impl&lt;T&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"indexmap/set/struct.Slice.html\" title=\"struct indexmap::set::Slice\">Slice</a>&lt;T&gt;",1,["indexmap::set::slice::Slice"]]],
"serde_bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"serde_bytes/struct.Bytes.html\" title=\"struct serde_bytes::Bytes\">Bytes</a>",1,["serde_bytes::bytes::Bytes"]]],
"serde_json":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"serde_json/value/struct.RawValue.html\" title=\"struct serde_json::value::RawValue\">RawValue</a>",1,["serde_json::raw::RawValue"]]],
"wasmparser":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"wasmparser/names/struct.KebabStr.html\" title=\"struct wasmparser::names::KebabStr\">KebabStr</a>",1,["wasmparser::validator::names::KebabStr"]]],
"wasmtime_environ":[],
"winnow":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"winnow/stream/struct.Bytes.html\" title=\"struct winnow::stream::Bytes\">Bytes</a>",1,["winnow::stream::Bytes"]],["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"winnow/stream/struct.BStr.html\" title=\"struct winnow::stream::BStr\">BStr</a>",1,["winnow::stream::BStr"]]],
"zerovec":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"zerovec/vecs/struct.FlexZeroSlice.html\" title=\"struct zerovec::vecs::FlexZeroSlice\">FlexZeroSlice</a>",1,["zerovec::flexzerovec::slice::FlexZeroSlice"]],["impl&lt;T, F = <a class=\"struct\" href=\"zerovec/vecs/struct.Index16.html\" title=\"struct zerovec::vecs::Index16\">Index16</a>&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"zerovec/struct.VarZeroSlice.html\" title=\"struct zerovec::VarZeroSlice\">VarZeroSlice</a>&lt;T, F&gt;",1,["zerovec::varzerovec::slice::VarZeroSlice"]],["impl&lt;T&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"zerovec/struct.ZeroSlice.html\" title=\"struct zerovec::ZeroSlice\">ZeroSlice</a>&lt;T&gt;",1,["zerovec::zerovec::slice::ZeroSlice"]],["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"zerovec/ule/struct.MultiFieldsULE.html\" title=\"struct zerovec::ule::MultiFieldsULE\">MultiFieldsULE</a>",1,["zerovec::ule::multi::MultiFieldsULE"]],["impl&lt;U&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"zerovec/ule/struct.OptionVarULE.html\" title=\"struct zerovec::ule::OptionVarULE\">OptionVarULE</a>&lt;U&gt;",1,["zerovec::ule::option::OptionVarULE"]],["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.73.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"zerovec/ule/struct.UnvalidatedStr.html\" title=\"struct zerovec::ule::UnvalidatedStr\">UnvalidatedStr</a>",1,["zerovec::ule::unvalidated::UnvalidatedStr"]]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()